<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE fakultet
[
<!ELEMENT fakultet (student+)>
<!ELEMENT student (osoba,upisi+)>
<!ELEMENT upisi (semestar+)>
<!ELEMENT osoba (ime,prezime,mestoRodjenja,datumRodjenja)>
<!ELEMENT ime (#PCDATA)>
<!ELEMENT prezime (#PCDATA)>
<!ELEMENT mestoRodjenja (#PCDATA)>
<!ELEMENT datumRodjenja (#PCDATA)>
<!ELEMENT semestar (#PCDATA)>

<!ATTLIST student 
status (studira|diplomirao) #REQUIRED
index ID #REQUIRED>

<!ATTLIST semestar 
broj CDATA #REQUIRED
godina CDATA #REQUIRED
vrsta (budzet|saf) #REQUIRED>
]>

<fakultet>
	<student status="studira" index="id1">
		<osoba>
			<ime>Milorad</ime>
			<prezime>Simic</prezime>
			<mestoRodjenja>Smederevo</mestoRodjenja>
			<datumRodjenja>25.5.1998.</datumRodjenja>
		</osoba>
		<upisi>
			<semestar broj="1" godina="2017" vrsta="saf"></semestar>
			<semestar broj="2" godina="2017" vrsta="saf"></semestar>
		</upisi>
		<upisi>
			<semestar broj="3" godina="2018" vrsta="saf"></semestar>
			<semestar broj="4" godina="2018" vrsta="saf"></semestar>
		</upisi>
	</student>
	<student status="studira" index="id2">
		<osoba>
			<ime>Petar</ime>
			<prezime>Petrovic</prezime>
			<mestoRodjenja>Novi Sad</mestoRodjenja>
			<datumRodjenja>7.6.1995</datumRodjenja>
		</osoba>
		<upisi>
			<semestar broj="1" godina="2017" vrsta="budzet"></semestar>
			<semestar broj="2" godina="2017" vrsta="budzet"></semestar>
		</upisi>
		<upisi>
			<semestar broj="3" godina="2018" vrsta="budzet"></semestar>
			<semestar broj="4" godina="2018" vrsta="budzet"></semestar>
		</upisi>
	</student>
</fakultet>